create database customer_behavior_analysis;
use customer_behavior_analysis;
alter table mytable rename to  customer;
select * from customer;

-- What is the total revenue generated by male vs. female customers?

select gender,sum(purchase_amount) as total_revenue
from customer 
group by gender ;

-- Which customers used a discount but still spent more than the average purchase amount?
 
select customer_id , purchase_amount 
from customer
where purchase_amount> (select avg(purchase_amount) from customer) and discount_applied = 'yes';

-- Which are the top 5 products with the highest average review rating?
select item_purchased , round(avg(review_rating),2) as rating
from customer 
group by item_purchased
order by rating desc 
limit 5 ;

-- Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type , avg(purchase_amount)
from customer 
where shipping_type in  ('express','standard')
group by shipping_type ;

-- Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select  subscription_status,count(customer_id) as total_customers, avg(purchase_amount) as avg_purchase, sum(purchase_amount) as total_revenue
from customer 
group by subscription_status ;

-- Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased , round(100*sum(case when discount_applied = 'yes' then 1 else 0 end )/ count(*),2) as percentage 
from customer 
group by item_purchased
order by percentage desc
limit 5 ;
select sum(purchase_amount) from customer;

-- Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
    select customer_id, previous_purchases,
    case 
    when previous_purchases =1 then 'new'
	when previous_purchases between 2 and 10 then 'returning' 
	else 'loyal' end  as customer_segment
	from customer 
)
select customer_segment,count(*) 'numer_of_customer'
from customer_type
group by customer_segment;

                                      -- WINDOW FUNCTION --
                                      
-- What are the top 3 most purchased products within each category?

with item_counts as (
select category,item_purchased,count(customer_id) as total_orders , row_number () over(partition by category order by count(customer_id) desc ) as item_rank 
from customer 
group by category,item_purchased)

select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<4;



-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) as repeat_buyer 
from customer
where previous_purchases >5
group by subscription_status;


-- What is the revenue contribution of each age group?

select age_group , sum(purchase_amount) as revenue 
from customer 
group by age_group
order by revenue desc; 